# Only one runner
variables:
   JAVA_HOME: "/usr/lib/jvm/java-7-openjdk-amd64/"

# default build 
jbotsim:
  stage: build
  tags:
    - ubuntu1404
  script:
    - $JAVA_HOME/bin/java -version
    - cd src && make
  artifacts:
    paths:
      - src/jbotsim.jar
    name: jbotsim

